In [1]:
#IMPORTAÇÕES
import pandas as pd
import numpy as np
#import seaborn as sns
#import matplotlib as plt
#%matplotlib inline

In [2]:
#caso trate horário
#import locale
#locale.setlocale(locale.LC_ALL, 'pt-BR') 
#import datetime

In [2]:
gym = pd.read_csv('academia.csv')

In [131]:
gym.tail(3)

number_people                       date  timestamp  day_of_week  \
62181             25  2017-03-18 19:02:40-07:00      68560            5   
62182             18  2017-03-18 19:12:47-07:00      69167            5   
62183             23  2017-03-18 19:22:51-07:00      69771            5   

       is_weekend  is_holiday  temperature  is_start_of_semester  \
62181           1           0        56.71                     0   
62182           1           0        56.71                     0   
62183           1           0        56.71                     0   

       is_during_semester  month  hour  
62181                   1      3    19  
62182                   1      3    19  
62183                   1      3    19

In [3]:
#convertendo a temperatura para Celsios
gym['temperature'] = round((gym['temperature']-32)/1.8,2)

In [133]:
gym.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62184 entries, 0 to 62183
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   number_people         62184 non-null  int64  
 1   date                  62184 non-null  object 
 2   timestamp             62184 non-null  int64  
 3   day_of_week           62184 non-null  int64  
 4   is_weekend            62184 non-null  int64  
 5   is_holiday            62184 non-null  int64  
 6   temperature           62184 non-null  float64
 7   is_start_of_semester  62184 non-null  int64  
 8   is_during_semester    62184 non-null  int64  
 9   month                 62184 non-null  int64  
 10  hour                  62184 non-null  int64  
dtypes: float64(1), int64(9), object(1)
memory usage: 5.2+ MB


In [158]:
#percentil50=np.percentile(gym['number_people'],50)
#round(percentil50)

28

In [159]:
#percentil70=np.percentile(gym['number_people'],70)
#round(percentil70)

40

In [4]:
#SEGUNDA POSSIBILIDADE DE VARIÁVEL PARA TARGET
percentil60 = round(np.percentile(gym['number_people'],60))
percentil60

33

In [136]:
gym[['hour', 'number_people','temperature']].groupby(['hour'])\
.mean().sort_values(by='number_people', ascending=False).head(10)

number_people  temperature
hour                            
18        48.297850    15.568431
17        47.637582    16.207771
19        44.741043    15.057361
16        42.959402    16.592518
21        42.922634    14.440410
20        41.669767    14.713352
22        40.463784    14.133222
15        37.197624    16.854204
11        36.219635    15.604196
12        36.110517    16.232635

In [5]:
# Criando Target /
# Coluna: <= percentil50 : Vazia / menor ou igual percentil 70 : MeioCheia / maior que percentil 70: cheia

gym['target'] = 'Cheia'

In [161]:
#for idx, _ in gym.iterrows():
#    if gym['number_people'].at[idx] <=percentil50:
#        gym['target'].at[idx] = "Vazia"
#    elif gym['number_people'].at[idx] <=percentil70 and gym['number_people'].at[idx] > percentil50: 
#        gym['target'].at[idx] = "Meio_cheia"

In [6]:
# SEGUNDA POSSIBILIDADE DE TARGET
for idx, _ in gym.iterrows():
    if gym['number_people'].at[idx] <= percentil60:
        gym['target'].at[idx] = "Vazia"

In [7]:
gym = gym.drop(columns=['date','is_weekend','is_holiday','is_start_of_semester','is_during_semester','timestamp'])
gym

number_people  day_of_week  temperature  month  hour target
0                 37            4        22.09      8    17  Cheia
1                 45            4        22.09      8    17  Cheia
2                 40            4        22.09      8    17  Cheia
3                 44            4        22.09      8    17  Cheia
4                 45            4        22.09      8    17  Cheia
...              ...          ...          ...    ...   ...    ...
62179             23            5        16.15      3    18  Vazia
62180             21            5        16.15      3    18  Vazia
62181             25            5        13.73      3    19  Vazia
62182             18            5        13.73      3    19  Vazia
62183             23            5        13.73      3    19  Vazia

[62184 rows x 6 columns]

In [8]:
gym['temperature'] = round(gym['temperature'])
gym.head(3)

number_people  day_of_week  temperature  month  hour target
0             37            4         22.0      8    17  Cheia
1             45            4         22.0      8    17  Cheia
2             40            4         22.0      8    17  Cheia

In [142]:
#gym['day_of_week'] = gym['day_of_week'].astype(str)
#gym['day_of_week'] = gym['day_of_week'].map({'0':'Seg','1':'Ter','2':'Qua','3':'Qui','4':'Sex','5':'Sab','6':'Dom'},na_action=None)
#gym.head(3)

In [9]:
gym['day_of_week'] = gym['day_of_week'].astype('category')
gym['month'] = gym['month'].astype('category')
gym['hour'] = gym['hour'].astype('category')
gym['temperature'] = gym['temperature'].astype('category')
gym['target'] = gym['target'].astype('category')

In [10]:
gym.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62184 entries, 0 to 62183
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype   
---  ------         --------------  -----   
 0   number_people  62184 non-null  int64   
 1   day_of_week    62184 non-null  category
 2   temperature    62184 non-null  category
 3   month          62184 non-null  category
 4   hour           62184 non-null  category
 5   target         62184 non-null  category
dtypes: category(5), int64(1)
memory usage: 792.7 KB


In [11]:
gym['target'].value_counts()

Vazia    37550
Cheia    24634
Name: target, dtype: int64

In [197]:
# primeiro desconsiderar dados sem pessoas
#gym = gym[(gym['number_people'] > 0)]

In [198]:
#gym['target'].value_counts()

Vazia    28775
Cheia    24634
Name: target, dtype: int64

In [13]:
gym = gym.drop(columns=['number_people'])

## ML - Naive Bayes

In [14]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

In [15]:
X = gym.drop(columns='target')
y = gym.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=5)

In [16]:
modelo = GaussianNB()

In [17]:
X_train.shape, y_train.shape

((49747, 4), (49747,))

In [18]:
X_test.shape, y_test.shape

((12437, 4), (12437,))

In [19]:
modelo.fit(X_train, y_train)
resultado = modelo.score(X_test, y_test)
print(f'Acurácia: {resultado}')

Acurácia: 0.7357883734019458


In [20]:
predicted= modelo.predict(X_test)
print(predicted)

['Vazia' 'Vazia' 'Cheia' ... 'Cheia' 'Vazia' 'Vazia']


In [21]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predicted))# Accuracy

[[3466 1447]
 [1839 5685]]


In [22]:
from sklearn.metrics import recall_score
recall_score(y_test, predicted, average=None)# Precision

array([0.70547527, 0.75558214])

In [23]:
from sklearn.metrics import precision_score
precision_score(y_test, predicted, average=None)

array([0.6533459 , 0.79711161])

In [24]:
from sklearn.metrics import classification_report
target = ['Vazia', 'Cheia']
print(classification_report(y_test, predicted, target_names=target))

              precision    recall  f1-score   support

       Vazia       0.65      0.71      0.68      4913
       Cheia       0.80      0.76      0.78      7524

    accuracy                           0.74     12437
   macro avg       0.73      0.73      0.73     12437
weighted avg       0.74      0.74      0.74     12437



### segunda possibildiade Naive Bayes

In [25]:
from sklearn.naive_bayes import MultinomialNB

In [27]:
modelo = MultinomialNB()
modelo.fit(X_train, y_train)
resultado = modelo.score(X_test, y_test)
print(f'Acurácia: {resultado}')

Acurácia: 0.7005708772211948


In [28]:
predicted= modelo.predict(X_test)
print(predicted)

['Cheia' 'Vazia' 'Cheia' ... 'Cheia' 'Vazia' 'Cheia']


In [29]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predicted))# Accuracy

[[3189 1724]
 [2000 5524]]


In [30]:
from sklearn.metrics import classification_report
target = ['Vazia', 'Cheia']
print(classification_report(y_test, predicted, target_names=target))

              precision    recall  f1-score   support

       Vazia       0.61      0.65      0.63      4913
       Cheia       0.76      0.73      0.75      7524

    accuracy                           0.70     12437
   macro avg       0.69      0.69      0.69     12437
weighted avg       0.70      0.70      0.70     12437

