In [1]:
#IMPORTAÇÕES
import pandas as pd
import numpy as np
#import seaborn as sns
#import matplotlib as plt
#%matplotlib inline

In [2]:
#caso trate horário
#import locale
#locale.setlocale(locale.LC_ALL, 'pt-BR') 
#import datetime

In [183]:
gym = pd.read_csv('academia.csv')

In [131]:
gym.tail(3)

number_people                       date  timestamp  day_of_week  \
62181             25  2017-03-18 19:02:40-07:00      68560            5   
62182             18  2017-03-18 19:12:47-07:00      69167            5   
62183             23  2017-03-18 19:22:51-07:00      69771            5   

       is_weekend  is_holiday  temperature  is_start_of_semester  \
62181           1           0        56.71                     0   
62182           1           0        56.71                     0   
62183           1           0        56.71                     0   

       is_during_semester  month  hour  
62181                   1      3    19  
62182                   1      3    19  
62183                   1      3    19

In [184]:
#convertendo a temperatura para Celsios
gym['temperature'] = round((gym['temperature']-32)/1.8,2)

In [133]:
gym.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62184 entries, 0 to 62183
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   number_people         62184 non-null  int64  
 1   date                  62184 non-null  object 
 2   timestamp             62184 non-null  int64  
 3   day_of_week           62184 non-null  int64  
 4   is_weekend            62184 non-null  int64  
 5   is_holiday            62184 non-null  int64  
 6   temperature           62184 non-null  float64
 7   is_start_of_semester  62184 non-null  int64  
 8   is_during_semester    62184 non-null  int64  
 9   month                 62184 non-null  int64  
 10  hour                  62184 non-null  int64  
dtypes: float64(1), int64(9), object(1)
memory usage: 5.2+ MB


In [158]:
percentil50=np.percentile(gym['number_people'],50)
round(percentil50)

28

In [159]:
percentil70=np.percentile(gym['number_people'],70)
round(percentil70)

40

In [189]:
#SEGUNDA POSSIBILIDADE DE VARIÁVEL PARA TARGET
percentil60 = round(np.percentile(gym['number_people'],60))
percentil60

33

In [136]:
gym[['hour', 'number_people','temperature']].groupby(['hour'])\
.mean().sort_values(by='number_people', ascending=False).head(10)

number_people  temperature
hour                            
18        48.297850    15.568431
17        47.637582    16.207771
19        44.741043    15.057361
16        42.959402    16.592518
21        42.922634    14.440410
20        41.669767    14.713352
22        40.463784    14.133222
15        37.197624    16.854204
11        36.219635    15.604196
12        36.110517    16.232635

In [190]:
# Criando Target /
# Coluna: <= percentil50 : Vazia / menor ou igual percentil 70 : MeioCheia / maior que percentil 70: cheia

gym['target'] = 'Cheia'

In [161]:
for idx, _ in gym.iterrows():
    if gym['number_people'].at[idx] <=percentil50:
        gym['target'].at[idx] = "Vazia"
    elif gym['number_people'].at[idx] <=percentil70 and gym['number_people'].at[idx] > percentil50: 
        gym['target'].at[idx] = "Meio_cheia"

In [191]:
# SEGUNDA POSSIBILIDADE DE TARGET
for idx, _ in gym.iterrows():
    if gym['number_people'].at[idx] <= percentil60:
        gym['target'].at[idx] = "Vazia"

In [192]:
gym = gym.drop(columns=['date','is_weekend','is_holiday'])
gym

number_people  timestamp  day_of_week  temperature  \
0                 37      61211            4        22.09   
1                 45      62414            4        22.09   
2                 40      63015            4        22.09   
3                 44      63616            4        22.09   
4                 45      64217            4        22.09   
...              ...        ...          ...          ...   
62179             23      67348            5        16.15   
62180             21      67955            5        16.15   
62181             25      68560            5        13.73   
62182             18      69167            5        13.73   
62183             23      69771            5        13.73   

       is_start_of_semester  is_during_semester  month  hour target  
0                         0                   0      8    17  Cheia  
1                         0                   0      8    17  Cheia  
2                         0                   0      8    17  Cheia  
3                         0                   0      8    17  Cheia  
4                         0                   0      8    17  Cheia  
...                     ...                 ...    ...   ...    ...  
62179                     0                   1      3    18  Vazia  
62180                     0                   1      3    18  Vazia  
62181                     0                   1      3    19  Vazia  
62182                     0                   1      3    19  Vazia  
62183                     0                   1      3    19  Vazia  

[62184 rows x 9 columns]

In [193]:
gym = gym.drop(columns=['is_start_of_semester','is_during_semester','timestamp'])
gym

number_people  day_of_week  temperature  month  hour target
0                 37            4        22.09      8    17  Cheia
1                 45            4        22.09      8    17  Cheia
2                 40            4        22.09      8    17  Cheia
3                 44            4        22.09      8    17  Cheia
4                 45            4        22.09      8    17  Cheia
...              ...          ...          ...    ...   ...    ...
62179             23            5        16.15      3    18  Vazia
62180             21            5        16.15      3    18  Vazia
62181             25            5        13.73      3    19  Vazia
62182             18            5        13.73      3    19  Vazia
62183             23            5        13.73      3    19  Vazia

[62184 rows x 6 columns]

In [194]:
gym['temperature'] = round(gym['temperature'])
gym.head(3)

number_people  day_of_week  temperature  month  hour target
0             37            4         22.0      8    17  Cheia
1             45            4         22.0      8    17  Cheia
2             40            4         22.0      8    17  Cheia

In [142]:
#gym['day_of_week'] = gym['day_of_week'].astype(str)
#gym['day_of_week'] = gym['day_of_week'].map({'0':'Seg','1':'Ter','2':'Qua','3':'Qui','4':'Sex','5':'Sab','6':'Dom'},na_action=None)
#gym.head(3)

In [195]:
gym['day_of_week'] = gym['day_of_week'].astype('category')
gym['month'] = gym['month'].astype('category')
gym['hour'] = gym['hour'].astype('category')
gym['temperature'] = gym['temperature'].astype('category')
gym['target'] = gym['target'].astype('category')

In [144]:
gym.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62184 entries, 0 to 62183
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype   
---  ------         --------------  -----   
 0   number_people  62184 non-null  int64   
 1   day_of_week    62184 non-null  category
 2   temperature    62184 non-null  category
 3   month          62184 non-null  category
 4   hour           62184 non-null  category
 5   target         62184 non-null  category
dtypes: category(5), int64(1)
memory usage: 792.7 KB


In [196]:
gym['target'].value_counts()

Vazia    37550
Cheia    24634
Name: target, dtype: int64

In [197]:
# primeiro desconsiderar dados sem pessoas
gym = gym[(gym['number_people'] > 0)]

In [198]:
gym['target'].value_counts()

Vazia    28775
Cheia    24634
Name: target, dtype: int64

In [172]:
gym

number_people day_of_week temperature month hour      target
0                 37           4        22.0     8   17  Meio_cheia
1                 45           4        22.0     8   17       Cheia
2                 40           4        22.0     8   17  Meio_cheia
3                 44           4        22.0     8   17       Cheia
4                 45           4        22.0     8   17       Cheia
...              ...         ...         ...   ...  ...         ...
62179             23           5        16.0     3   18       Vazia
62180             21           5        16.0     3   18       Vazia
62181             25           5        14.0     3   19       Vazia
62182             18           5        14.0     3   19       Vazia
62183             23           5        14.0     3   19       Vazia

[62184 rows x 6 columns]

In [199]:
gym = gym.drop(columns=['number_people'])

## ML - Naive Bayes

In [165]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

In [217]:
X = gym.drop(columns='target')
y = gym.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=5)

In [167]:
modelo = GaussianNB()

In [149]:
X_train.shape, y_train.shape

((49747, 5), (49747,))

In [150]:
X_test.shape, y_test.shape

((12437, 5), (12437,))

In [218]:
modelo.fit(X_train, y_train)
resultado = modelo.score(X_test, y_test)
print(f'Acurácia: {resultado}')

Acurácia: 0.7038944017974162


In [219]:
predicted= modelo.predict(X_test)
print(predicted)

['Vazia' 'Cheia' 'Cheia' ... 'Cheia' 'Vazia' 'Cheia']


In [220]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predicted))# Accuracy

[[3632 1262]
 [1901 3887]]


In [221]:
from sklearn.metrics import recall_score
recall_score(y_test, predicted, average=None)# Precision

array([0.74213322, 0.67156185])

In [222]:
from sklearn.metrics import precision_score
precision_score(y_test, predicted, average=None)

array([0.65642509, 0.75490386])

In [223]:
from sklearn.metrics import classification_report
target = ['Vazia', 'Cheia']
print(classification_report(y_test, predicted, target_names=target))

              precision    recall  f1-score   support

       Vazia       0.66      0.74      0.70      4894
       Cheia       0.75      0.67      0.71      5788

    accuracy                           0.70     10682
   macro avg       0.71      0.71      0.70     10682
weighted avg       0.71      0.70      0.70     10682

